[package]
name = "pecan-parser"
version = "0.1.0"
authors = ["Caleb Jones <code@calebjones.net>"]
repository = "https://github.com/porglezomp/pecan-lang"
keywords = ["parser", "pecan-lang"]

[[bin]]
name = "pecan-parser"
doc = false
